---
titsle: "Small Mammal Community Analyses"
author: "Ethan Aberccrombie"
date: "2/24/2022"
output: html_document
---

```{r packages, include=FALSE}
#packages
require(tidyverse)
require(reshape2)
```

```{r data, include=FALSE}
#load data
pfa_data <- read_csv('/Users/ethanabercrombie/Library/CloudStorage/Box-Box/Grinnell-Mammal-Community-Shifts/Rowe et al. 2017 - FINAL Occupancy Analyses/PFA ANALYSES/WPFA_results_08Mar2011.csv') %>% 
  rename(transect_boundary = "...1") %>% 
  filter(str_detect(transect_boundary,
                    '0') |
           str_detect(transect_boundary,
                      '1')) %>% 
  mutate(Region = case_when(str_detect(transect_boundary,
                                         'SS') ~ 'SS',
                              str_detect(transect_boundary,
                                         'LA') ~ 'LA',
                              str_detect(transect_boundary,
                                         'YO') ~ 'YO'),
         Era = case_when(str_detect(transect_boundary,
                                    '0') ~ 'H',
                         str_detect(transect_boundary,
                                    '1') ~ 'M'),
         Marmotaflaviventris = c(1561,1971,
                                 1561,1971+520,
                                 2469,3353,
                                 2469,3353,
                                 2268,3503,
                                 2268,3503) ,
         Ochotonaprinceps = c(1478,2514,
                              1478,2514,
                              2377,3871,
                              2377,3871,
                              2732,3384,
                              2732,3384),
         Sciurusgriseus = c(103,1051,
                            103,1051+671,
                            183,1951,
                            183,1951-262,
                            787,2364,
                            787+720,2364-750),
         Tamiasciurusdouglasii = c(886,2061,
                                   886,2061+430,
                                   1229,3185,
                                   1229,3185,
                                   1592,3384,
                                   1592,3384),
         Thomomysbottae = c(75,1335,
                            75,1335,
                            57,1676,
                            57,1676,
                            118,3384,
                            118,3384),
         Thomomysmonticola = c(1561,2514,
                               1561,2514,
                               1905,3155,
                               1905,3155,
                               NA,NA,
                               NA,NA))
pfa_data <- pfa_data %>% 
  bind_rows(filter(pfa_data,
                   Era == 'M')) %>% 
  mutate(Era = if_else(duplicated(transect_boundary),
                       "HM",
                       Era))

pfa_data <- melt(pfa_data,
          id.vars = c('transect_boundary',
                      'Region',
                      'Era'),
          value.name = 'species_elevation',
          variable.name = 'species_name') %>% 
  group_by(Region,
           Era,
           species_name) %>% 
  mutate(species_min = min(species_elevation),
         species_max = max(species_elevation)) %>% 
  dplyr::select(-transect_boundary,
         -species_elevation) %>% 
  distinct() %>% #Select distinct rows.
  filter(Region != 'LA') #Remove Lassen until we figure out what's happening at this site.

#Define species list. Sort alphabetically and remove "_" to match PFA data.
species_list <- c('Sorex_ornatus',
                  'Dipodomys_heermanni',
                  'Microtus_californicus',
                  'Reithrodontomys_megalotis',
                  'Chaetodipus_californicus',
                  'Neotoma_fuscipes',
                  'Neotoma_macrotis',
                  'Peromyscus_truei',
                  'Sciurus_griseus',
                  'Dipodomys_agilis',
                  'Tamias_merriami',
                  'Peromyscus_boylii',
                  'Thomomys_bottae',
                  'Otospermophilus_beecheyi',
                  'Sorex_trowbridgii',
                  'Tamias_quadrimaculatus',
                  'Sorex_vagrans',
                  'Tamias_senex',
                  'Tamiasciurus_douglasii',
                  'Zapus_princeps',
                  'Microtus_montanus',
                  'Microtus_longicaudus',
                  'Thomomys_monticola',
                  'Neotoma_cinerea',
                  'Tamias_speciosus',
                  'Tamias_amoenus',
                  'Sorex_palustris',
                  'Marmota_flaviventris',
                  'Urocitellus_beldingi',
                  'Callospermophilus_lateralis',
                  'Sorex_monticolus',
                  'Ochotona_princeps',
                  'Tamias_alpinus') %>% 
  str_sort() %>% 
  str_remove('[_]') #Remove '_' to match object 'pfa_data'

#load site data. Filter to exclude species and psi columns
site_data <- read_csv('/Users/ethanabercrombie/Library/CloudStorage/Box-Box/Grinnell-Mammal-Community-Shifts/Rowe et al. 2017 - FINAL Occupancy Analyses/R Scripts and Mark Data/PSI-by-Site-08mar2011.csv') %>% 
  filter(Species == 'Callospermophiluslateralis') %>% #This results in a single copy of site information.
  dplyr::select(Region:AggregateName) %>% 
  rename(site_name = AggregateName) %>% 
  filter(Region != 'LA') %>% #Remove Lassen until we figure out what's happening at this site.
  bind_rows(filter(site_data,
                   Era == 'H')) %>% #Make duplicates of historical site, and rename Era to "HM". This will be used to calculate contemporary CCIs for historical sites.
  mutate(Era = if_else(duplicated(site_name),
                       "HM",
                       Era)) %>% 
  mutate(site_name = if_else(duplicated(site_name),
                             paste0(site_name,
                                    "_HM"),
                             site_name))
  
  #Add empty columns for each species.
  site_data[species_list] = NA
  #Remove column 117 - "LAHistoricBattleCreek" because it is a duplicate.
  #site_data <- site_data[-117,]
#load climate data.
sp_climate_data <- read_csv('/Users/ethanabercrombie/Library/CloudStorage/Box-Box/Grinnell-Mammal-Community-Shifts/Data/Climate Data/species_climate_preferences.csv') %>% 
  mutate_at("species_name", str_replace, "_", "") #Remove '_' to match object 'pfa_data'
```

To calculate the community climate indices (CTI/CPI) we use the PFA (probability false absence) results for each species at a site. If a site is found between a species elevational range, we conclude that it is present. the CCI's for each site is the median value of the included species preferences.

```{r CCI, include=FALSE}
#For loop for every site CCI
for (i in 1:nrow(site_data)) {
  print(i)
  #Create a temporary object that is the filtered results of pfa_data (elevational distributions) that matches the Region and Era for each site. These distributions are used to determine which species are present at each site.
  pfa_loop <- pfa_data %>% 
    filter(Region %in% site_data[i,] &
             Era %in% site_data[i,])
  
  #Assign a value of 1 (present) to species within the elevation range defined in 'pfa_data'
  for (sp in unique(species_list)) {
    #print(sp)
    pfa_loop_2 <- pfa_loop %>% 
    filter(species_name == sp)
    site_data[i,sp] <- case_when(site_data[i, 'Elev'] >= pfa_loop_2$species_min &
                                      site_data[i, 'Elev'] <= pfa_loop_2$species_max ~ 1,
                                      site_data[i, 'Elev'] < pfa_loop_2$species_min ~ 0,
                                      site_data[i, 'Elev'] > pfa_loop_2$species_max ~ 0)
  }
  
}

#Calculate Community Climate indices.
#Values of 'NA' are the result of sites with 0 species present.

#Define community data.
community_data <- site_data %>% 
  select(Callospermophiluslateralis:Zapusprinceps) %>% 
  t() %>% 
  as.data.frame()
colnames(community_data) <- site_data$site_name
  
#Create a dataframe for MAT and MAP separately. Because species_name are in the same order, multiple sp_climate_data with community_data.
community_data_MAT <- community_data * sp_climate_data$MAT
community_data_MAT[community_data_MAT == 0] <- NA

community_data_MAP <- community_data * sp_climate_data$MAP
community_data_MAP[community_data_MAP == 0] <- NA

#Calculate the CTI
community_temperature_index <- community_data_MAT %>% 
  summarise(across(.cols = everything(),
                   ~ median(.x,
                            na.rm = T))) %>% 
  t() %>% 
  as.data.frame() %>% 
  rename(CTI = V1)

#Calculate the CPI.
community_precipitation_index <- community_data_MAP %>% 
  summarise(across(.cols = everything(),
                   ~ median(.x,
                            na.rm = T))) %>% 
  t() %>% 
  as.data.frame() %>% 
  rename(CPI = V1)

#Merge CTI and CPI with site_data
final_community_data <- bind_cols(community_temperature_index,
                        community_precipitation_index,
                        site_data) %>% 
  select(site_name,
         everything()) %>% 
  mutate(site_name = as.factor(site_name),
         Region = as.factor(Region),
         Era = as.factor(Era))

write_csv(final_community_data,
          '~/Desktop/Grinnell-Mammal-Community-Shifts/Data/site_data/community_data.csv')
  
final_community_data %>% 
  ggplot(aes(x = Elev,
             y = CPI)) +
  geom_point(aes(color = Era)) +
  facet_grid(rows = vars(Region))

final_community_data %>% 
  ggplot(aes(x = Elev,
             y = CTI)) +
  geom_point(aes(color = Era)) +
  facet_grid(rows = vars(Region))

(final_community_data %>% 
  group_by(Region,
           Era) %>% 
  summarise(number_species = length(Region),
            elv_range <- range(Elev)))

```

# Analysis

# Boxplots

```{r}
range = c(0,250,750,1250,1750,2250,2750,3250)
range_lab <- c('0-250','250-750','750-1250','1250-1750','1750-2250','2250-2750','>2750')

filter(final_community_data,
       Era == 'H' |
         Era == 'HM') %>% 
  ggplot(aes(x = cut(Elev,
                     breaks = range),
             y = CTI)) +
  geom_boxplot(aes(color = Era)) +
  scale_x_discrete(labels = range_lab) +
  facet_grid(rows = vars(Region)) +
  labs(x = 'Elevation')

final_community_data %>% 
  ggplot(aes(x = cut(Elev,
                     breaks = range),
             y = CPI)) +
  geom_boxplot(aes(color = Era)) +
  scale_x_discrete(labels = range_lab) +
  facet_grid(rows = vars(Region)) +
  labs(x = 'Elevation')
```


## Spline

```{r}
final_community_data %>%  
  ggplot(mapping = aes(x = Elev,
                       y = CTI)) +
  geom_point(aes(color = Era)) +
  geom_smooth(aes(color = Era)) +
  facet_grid(rows = 'Region')

range <- 1:5

####
#Choose best CTI model using AIC.
####
spline_df_CTI <- tibble(
  df_CTI_YO_H = range,
  AIC_CTI_YO_H = NA,
  df_CTI_YO_M = range,
  AIC_CTI_YO_M = NA,
  df_CTI_SS_H = range,
  AIC_CTI_SS_H = NA,
  df_CTI_SS_M = range,
  AIC_CTI_SS_M = NA
)

for (i in 1:nrow(spline_df_CTI)) {
  
  #YO historic
  model <- glm(data = filter(final_community_data,
                             Region == 'YO',
                             Era == 'H'),
               CTI ~ splines::ns(Elev,
                                df = i))
  spline_df_CTI[i,'AIC_CTI_YO_H'] <- AIC(model)
  
  #YO modern
  model <- glm(data = filter(final_community_data,
                             Region == 'YO',
                             Era == 'M'),
               CTI ~ splines::ns(Elev,
                                df = i))
  spline_df_CTI[i,'AIC_CTI_YO_M'] <- AIC(model)
  
  #SS historic
  model <- glm(data = filter(final_community_data,
                             Region == 'SS',
                             Era == 'H'),
               CTI ~ splines::ns(Elev,
                                df = i))
  spline_df_CTI[i,'AIC_CTI_SS_H'] <- AIC(model)
  
  #SS modern
  model <- glm(data = filter(final_community_data,
                             Region == 'SS',
                             Era == 'M'),
               CTI ~ splines::ns(Elev,
                                df = i))
  spline_df_CTI[i,'AIC_CTI_SS_M'] <- AIC(model)
}

####
#Choose best CPI model using AIC.
####

spline_df_CPI <- tibble(
  df_CPI_YO_H = range,
  AIC_CPI_YO_H = NA,
  df_CPI_YO_M = range,
  AIC_CPI_YO_M = NA,
  df_CPI_SS_H = range,
  AIC_CPI_SS_H = NA,
  df_CPI_SS_M = range,
  AIC_CPI_SS_M = NA
)

for (i in 1:nrow(spline_df_CPI)) {
  
  #YO historic
  model <- glm(data = filter(final_community_data,
                             Region == 'YO',
                             Era == 'H'),
               CPI ~ splines::ns(Elev,
                                df = i))
  spline_df_CPI[i,'AIC_CPI_YO_H'] <- AIC(model)
  
  #YO modern
  model <- glm(data = filter(final_community_data,
                             Region == 'YO',
                             Era == 'M'),
               CPI ~ splines::ns(Elev,
                                df = i))
  spline_df_CPI[i,'AIC_CPI_YO_M'] <- AIC(model)
  
  #SS historic
  model <- glm(data = filter(final_community_data,
                             Region == 'SS',
                             Era == 'H'),
               CPI ~ splines::ns(Elev,
                                df = i))
  spline_df_CPI[i,'AIC_CPI_SS_H'] <- AIC(model)
  
  #SS modern
  model <- glm(data = filter(final_community_data,
                             Region == 'SS',
                             Era == 'M'),
               CPI ~ splines::ns(Elev,
                                df = i))
  spline_df_CPI[i,'AIC_CPI_SS_M'] <- AIC(model)
}

#Select the lowest AIC

##YO Historic
### CTI
YOH_CTI_model <- model <- glm(data = filter(final_community_data,
                             Region == 'YO',
                             Era == 'H'),
               CTI ~ splines::ns(Elev,
                                df = spline_df_CTI[[which.min(spline_df_CTI$AIC_CTI_YO_H),'df_CTI_YO_H']]))
### CPI
YOH_CPI_model <- model <- glm(data = filter(final_community_data,
                             Region == 'YO',
                             Era == 'H'),
               CPI ~ splines::ns(Elev,
                                df = spline_df_CPI[[which.min(spline_df_CPI$AIC_CPI_YO_H),'df_CPI_YO_H']]))  

##YO Modern
### CTI
YOM_CTI_model <- model <- glm(data = filter(final_community_data,
                             Region == 'YO',
                             Era == 'M'),
               CTI ~ splines::ns(Elev,
                                df = spline_df_CTI[[which.min(spline_df_CTI$AIC_CTI_YO_M),'df_CTI_YO_M']]))
### CPI
YOM_CPI_model <- model <- glm(data = filter(final_community_data,
                             Region == 'YO',
                             Era == 'M'),
               CPI ~ splines::ns(Elev,
                                df = spline_df_CPI[[which.min(spline_df_CPI$AIC_CPI_YO_M),'df_CPI_YO_M']])) 
##SS Historic
### CTI
SSH_CTI_model <- model <- glm(data = filter(final_community_data,
                             Region == 'SS',
                             Era == 'H'),
               CTI ~ splines::ns(Elev,
                                df = spline_df_CTI[[which.min(spline_df_CTI$AIC_CTI_SS_H),'df_CTI_SS_H']]))
### CPI
SSH_CPI_model <- model <- glm(data = filter(final_community_data,
                             Region == 'SS',
                             Era == 'H'),
               CPI ~ splines::ns(Elev,
                                df = spline_df_CPI[[which.min(spline_df_CPI$AIC_CPI_SS_H),'df_CPI_SS_H']])) 
## SS Modern
### CTI
SSM_CTI_model <- model <- glm(data = filter(final_community_data,
                             Region == 'SS',
                             Era == 'M'),
               CTI ~ splines::ns(Elev,
                                df = spline_df_CTI[[which.min(spline_df_CTI$AIC_CTI_SS_M),'df_CTI_SS_M']]))
### CPI
SSM_CPI_model <- model <- glm(data = filter(final_community_data,
                             Region == 'SS',
                             Era == 'M'),
               CPI ~ splines::ns(Elev,
                                df = spline_df_CPI[[which.min(spline_df_CPI$AIC_CPI_SS_M),'df_CPI_SS_M']])) 
```

#Spline Graphs

```{r}
#CTI
##Sequoi & Kings Canyon
final_community_data %>% 
  filter(Region == 'SS') %>% 
  ggplot()+
  geom_point(aes(x = Elev,
                 y = CTI,
                 fill = Era,
                 color = Era)) +
  geom_line(data = filter(final_community_data,
                          Region == 'SS',
                          Era == 'H'),
            aes(x = Elev,
                y = predict.glm(SSH_CTI_model)),
            size = 1.5,
            alpha = 0.5,
            color = 'red') +
  geom_line(data = filter(final_community_data,
                          Region == 'SS',
                          Era == 'M',
                          CTI != 'NA'),
            aes(x = Elev,
                y = predict.glm(SSM_CTI_model)),
            size = 1.5,
            alpha = 0.5,
            color = 'blue') +
  annotate('text',
           x = 5,
           y = 5,
           label = paste(df.residual(SSM_CTI_model))) +
  labs(title = "CTI - Sequoia")

#Yosemite
final_community_data %>% 
  filter(Region == 'YO') %>% 
  ggplot()+
  geom_point(aes(x = Elev,
                 y = CTI,
                 fill = Era,
                 color = Era)) +
  geom_line(data = filter(final_community_data,
                          Region == 'YO',
                          Era == 'H',
                          CTI != 'NA'),
            aes(x = Elev,
                y = predict.glm(YOH_CTI_model)),
            color = 'red') +
  geom_line(data = filter(final_community_data,
                          Region == 'YO',
                          Era == 'M',
                          CTI != 'NA'),
            aes(x = Elev,
                y = predict.glm(YOM_CTI_model)),
            color = 'blue') +
  labs(title = "CTI - Yosemite")

#CPI
##Sequoi & Kings Canyon
final_community_data %>% 
  filter(Region == 'SS') %>% 
  ggplot()+
  geom_point(aes(x = Elev,
                 y = CPI,
                 fill = Era,
                 color = Era)) +
  geom_line(data = filter(final_community_data,
                          Region == 'SS',
                          Era == 'H'),
            aes(x = Elev,
                y = predict.glm(SSH_CPI_model)),
            color = 'red') +
  geom_line(data = filter(final_community_data,
                          Region == 'SS',
                          Era == 'M',
                          CPI != 'NA'),
            aes(x = Elev,
                y = predict.glm(SSM_CPI_model)),
            color = 'blue') + 
  labs(title = "CPI - Sequoia")

#Yosemite
final_community_data %>% 
  filter(Region == 'YO') %>% 
  ggplot()+
  geom_point(aes(x = Elev,
                 y = CPI,
                 fill = Era,
                 color = Era)) +
  geom_line(data = filter(final_community_data,
                          Region == 'YO',
                          Era == 'H',
                          CPI != 'NA'),
            aes(x = Elev,
                y = predict.glm(YOH_CPI_model)),
            color = 'red') +
  geom_line(data = filter(final_community_data,
                          Region == 'YO',
                          Era == 'M',
                          CPI != 'NA'),
            aes(x = Elev,
                y = predict.glm(YOM_CPI_model)),
            color = 'blue') +
  labs(title = "CPI - Yosemite")
```

```{r}
(SS_method_plot <- pfa_data %>% 
    na.omit() %>% 
  filter(Region == "SS",
         Era == "H" |
           Era == "M",
         species_name != 'Sorextenellus') %>% #only found at one site (no elevational range) and doesn't show up correctly on this methods figure 
   mutate(Era = as.factor(Era)) %>% 
ggplot(aes(color = Era,
           size = Era)) +
  geom_linerange(aes(x = reorder(species_name,
                                 species_min),
                   ymin = species_min,
                   ymax = species_max)) +
    geom_hline(yintercept = 3000,
               linetype = 2) +
    scale_x_discrete(labels = c(paste0('sp', 1:length(unique(pfa_data$species_name))))) +
    scale_color_manual(values = c('#664596ff','#eb8055ff')) +
    # scale_alpha_manual(values = c(0.5,.8)) +
    scale_size_manual(values = c(4,2)) +
    theme(axis.text.x = element_text(angle = 45,
                                     vjust = 0.5),
          legend.position = 'top',
          panel.background = element_blank(),
          axis.title.x = element_blank())
  )

(YO_method_plot <- pfa_data %>% 
    na.omit() %>% 
  filter(Region == "YO",
         Era == "H" |
           Era == "M",
         species_name != 'Sorextenellus') %>% #only found at one site (no elevational range) and doesn't show up correctly on this methods figure 
   mutate(Era = as.factor(Era)) %>% 
ggplot(aes(color = Era,
           size = Era)) +
  geom_linerange(aes(x = reorder(species_name,
                                 species_min),
                   ymin = species_min,
                   ymax = species_max)) +
    geom_hline(yintercept = 3000,
               linetype = 2) +
    scale_x_discrete(labels = c(paste0('sp', 1:length(unique(pfa_data$species_name))))) +
    scale_color_manual(values = c('#664596ff','#eb8055ff')) +
    # scale_alpha_manual(values = c(0.5,.8)) +
    scale_size_manual(values = c(4,2)) +
    theme(axis.text.x = element_text(angle = 45,
                                     vjust = 0.5),
          legend.position = 'top',
          panel.background = element_blank(),
          axis.title.x = element_blank())
  )

ggsave(YO_method_plot,
       filename = '/Users/ethanabercrombie/Library/CloudStorage/Box-Box/EthanAbercrombie/Presentations/ESA_2022/YO_method_plot.jpg',
       width = 10,
       height = 5,
       units = 'in',
       dpi = 300)

ggsave(SS_method_plot,
       filename = '/Users/ethanabercrombie/Library/CloudStorage/Box-Box/EthanAbercrombie/Presentations/ESA_2022/SS_method_plot.jpg',
       width = 10,
       height = 5,
       units = 'in',
       dpi = 300)

# SSModernTaylorMeadow
# 
# final_community_data %>% 
#   filter(site_name == 'SSModernTaylorMeadow')
# 
# final_community_data %>% 
#   ggplot() +
#   geom_point(aes(x = Elev,
#                  y = CTI,
#                  fill = Era))


####
#Extract predicted historical CTI for modern sites using the elevation for modern sites.
#Sequoia
SSH_CTI_model$call

SS_Modern_data <- final_community_data %>% 
  filter(Region == 'SS',
         Era == 'M')

historic_prediction <- as.numeric(
  predict.glm(SSH_CTI_model,
              newdata = SS_Modern_data)
)

SS_Modern_data$CTI_change <- SS_Modern_data$CTI - historic_prediction
plot(SS_Modern_data$CTI_change ~ SS_Modern_data$Elev)

##SS CPI
SSH_CPI_model$call

historic_prediction <- as.numeric(
  predict.glm(SSH_CPI_model,
              newdata = SS_Modern_data)
)

SS_Modern_data$CPI_change <- SS_Modern_data$CPI - historic_prediction
plot(SS_Modern_data$CPI_change ~ SS_Modern_data$Elev)

#Yosemite
YOH_CTI_model$call

YO_Modern_data <- final_community_data %>% 
  filter(Region == 'YO',
         Era == 'M')

historic_prediction <- as.numeric(
  predict.glm(YOH_CTI_model,
              newdata = YO_Modern_data)
)

YO_Modern_data$CTI_change <- YO_Modern_data$CTI - historic_prediction
plot(YO_Modern_data$CTI_change ~ YO_Modern_data$Elev)

##YO CPI
YOH_CPI_model$call

historic_prediction <- as.numeric(
  predict.glm(YOH_CPI_model,
              newdata = YO_Modern_data)
)

YO_Modern_data$CPI_change <- YO_Modern_data$CPI - historic_prediction
plot(YO_Modern_data$CPI_change ~ YO_Modern_data$Elev)


```

